# railway.yaml
version: 1

services:
  app:
    # Service name shown in the Railway dashboard
    name: cookhub-api
    
    # Use the official Python runtime
    runtime: python
    
    # Build command to install dependencies
    buildCommand: pip install -r requirements.txt
    
    # Start command for the application
    startCommand: python app.py
    
    # Health check endpoint
    healthcheckPath: /
    
    # Restart policy
    restart: unless-stopped
    
    # Environment variables
    env:
      FLASK_ENV: production
      PYTHONUNBUFFERED: true
    
    # Service configuration
    domains:
      - cookhub-api.railway.internal
      
    # Resource allocation
    resources:
      memory: 512MB
      cpu: 0.5

  # Database service (MySQL)
  mysql:
    # Use MySQL plugin
    image: mysql:8.0
    
    # Database configuration
    env:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cookhub
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
    
    # Restart policy
    restart: unless-stopped
    
    # Resource allocation
    resources:
      memory: 256MB
      cpu: 0.25

# Define service dependencies
dependencies:
  app:
    - mysql

# Deployment configuration
deploy:
  # Number of replicas
  replicas: 1
  
  # Auto-deploy from GitHub
  triggers:
    - type: github
    
  # Health checks
  healthChecks:
    - path: /
      port: ${PORT}
      timeout: 30s
      interval: 60s
      retries: 3

# Custom domain configuration
domain:
  # Your custom domain (replace with your actual domain)
  name: api.cookhub.com
  # Or if you want Railway subdomain:
  # name: cookhub-production.up.railway.app
  
  # SSL/TLS configuration
  tls:
    managed: true
  
  # Redirect configuration
  redirects:
    - from: www.api.cookhub.com
      to: api.cookhub.com
      status: 301

# Network configuration
networking:
  - port: ${PORT}
    protocol: HTTP
    
  # Internal service communication
  - port: 3306
    protocol: TCP
    service: mysql

# Build configuration
build:
  # Build cache configuration
  cache:
    enabled: true
    paths:
      - ~/.cache/pip
  
  # Build arguments
  args:
    - PYTHON_VERSION=3.11

# Monitoring and logging
observability:
  # Enable metrics
  metrics: true
  
  # Enable logs
  logs: true
  
  # Health checks
  health:
    enabled: true
    path: /health
    port: ${PORT}

# Environment-specific configurations
environments:
  production:
    deploy:
      replicas: 2
      resources:
        memory: 1GB
        cpu: 1.0
    domain:
      name: api.cookhub.com
      
  staging:
    domain:
      name: cookhub-staging.up.railway.app